import Link from "next/link";
import { journeys } from "./journey-data";
import HeroBall from "./components/hero-ball";
import ScrollFX from "./components/scroll-fx";
import SiteNav from "./components/site-nav";

const Arrow = () => <span className="arrow" aria-hidden="true">↗</span>;

export default function Home() {
  return <main>
    <section className="hero" id="top">
      <SiteNav variant="hero" />
      <div className="hero-content wrap"><p className="eyebrow fade-up">Private journeys · Unhurried wonders</p><h1 className="hero-title"><span className="fade-up d1">Find the place</span><em className="fade-up d2">beyond the map.</em></h1><div className="hero-bottom fade-up d3"><p>For those who collect feelings,<br />not just destinations.</p><Link className="circle-link" href="/journeys">Explore<br />journeys <Arrow /></Link></div></div>
      <div className="hero-meta"><span>Designed around emotions</span><span>Scroll to wander <i /></span></div>
      <HeroBall />
    </section>
    <section className="intro wrap" id="philosophy"><p className="eyebrow" data-reveal="up">The Velora difference</p><div className="intro-grid"><h2 data-reveal="left">Not a holiday.<br /><em>A change of pace.</em></h2><div className="intro-copy" data-reveal="right"><p>We design journeys with room for serendipity. A private supper under a desert sky. The road that takes longer, because it is better.</p><a className="text-link" href="#plan">Our point of view <Arrow /></a></div></div></section>
    <section className="specializations"><div className="wrap"><p className="eyebrow" data-reveal="up">What we do best</p><div className="specialization-head"><h2 data-reveal="left">Every journey,<br /><em>exactly your way.</em></h2><p data-reveal="right">We create sophisticated travel experiences with the access, care and imagination to make each detail feel personal.</p></div><div className="specialization-grid" data-stagger><article><span>01</span><h3>International<br />journeys</h3><p>Europe, Nordics, Japan, Australia & New Zealand, the Middle East, Southeast and Central Asia.</p></article><article><span>02</span><h3>Luxury<br />escapes</h3><p>Private villas, distinctive resorts, luxury rail, exceptional stays and exclusive cruises.</p></article><article><span>03</span><h3>Signature<br />honeymoons</h3><p>Privacy, romance and meaningful moments, designed around the two of you.</p></article><article><span>04</span><h3>Curated India<br />& incentives</h3><p>Handcrafted India journeys plus premium business travel, leadership retreats and incentives.</p></article></div></div></section>
    <section className="journeys" id="journeys"><div className="wrap section-head"><div data-reveal="left"><p className="eyebrow">Selected journeys</p><h2>Go where<br /><em>the story is.</em></h2></div><p className="section-note" data-reveal="right">A complete collection of considered routes,<br />rare access, and brilliant local company.</p></div><div className="journey-grid journey-grid-four wrap" data-stagger>{journeys.map((item) => <Link href={`/journeys/${item.slug}`} className="journey-card" key={item.number} style={{ backgroundImage: `linear-gradient(180deg, rgba(29,45,68,.04) 30%, rgba(29,45,68,.84) 100%), url(${item.image})` }}><div className="card-top"><span>{item.number}</span><span>{item.duration}</span></div><div className="card-bottom"><h3>{item.title}</h3><Arrow /></div></Link>)}</div><div className="wrap all-journeys" data-reveal="up"><Link className="text-link" href="/journeys">View all journeys <Arrow /></Link></div></section>
    <section className="manifesto"><div className="manifesto-image" data-clip /><div className="manifesto-panel" data-stagger><p className="eyebrow">An invitation</p><h2>The world still has<br /><em>its secrets.</em></h2><p>We know where to listen for them. Every Velora journey is shaped around the way you want to feel when you return home.</p><Link href="/enquire" className="pill">Meet your travel designer <Arrow /></Link></div></section>
    <section className="clientele wrap"><p className="eyebrow" data-reveal="up">Our clientele</p><div className="clientele-layout"><h2 data-reveal="left">For travellers who<br /><em>expect more.</em></h2><div className="client-tags" data-stagger><span>Affluent families</span><span>Honeymoon couples</span><span>Entrepreneurs</span><span>Corporate leaders</span><span>Luxury experience seekers</span><span>Multi-generational travellers</span><span>Special interest travellers</span></div></div></section>
    <footer id="plan"><div className="wrap footer-top"><p className="eyebrow" data-reveal="up">Your story begins here</p><h2 data-drift="7">Let&apos;s go<br /><em>somewhere.</em></h2><Link className="footer-button" href="/enquire" data-reveal="zoom">Plan a private journey <Arrow /></Link></div><div className="wrap footer-bottom"><Link className="brand" href="/">VELORA<span>°</span></Link><p>© 2026 Velora Travel Collective</p><div><a href="#top">Instagram</a><a href="#top">Contact</a></div></div></footer>
    <ScrollFX />
  </main>;
}
